### PR TITLE
Mock `Conf` to prevent it from writing to disk

### LINKED ISSUE #1: Tests depending upon custom config cannot be executed concurrently
Because I use `Conf` right [here](https://github.com/SamVerschueren/kap-plugin-mock-context/blob/master/index.js#L23) without a custom [configName](https://github.com/sindresorhus/conf#configname) we are not able to execute tests concurrently at the moment because the config JSON files are interfering. How should I solve this? Use [cwd](https://github.com/sindresorhus/conf#cwd) together with `tempy` in order to randomly create a new JSON location?

// @sindresorhus @kevva

### PR DESCRIPTION
**Pull request by kevva**
Since we're using it in tests only we don't want settings to persist on the disk.

Fixes #1.

### CODE REVIEW

**Comment by SamVerschueren** [comment]
Should we put MockConf and the date function in separate files in a utils directory? It becomes a little cluttered this way and distracts you from the actual main code.

**Comment by kevva** [comment]
Sure, should I do it in this? And do you want it in a directory (`lib/util.js`(?)) or just a `util.js` file?

**Comment by SamVerschueren** [comment]
Sure, let's do it in here. Not sure, was thinking in line of `utils/date.js` and `utils/mock-conf.js`. What do you think?

**Comment by kevva** [comment]
Personally I don't mind just having it in one file at the root because I don't think we'll ever need more utils, at least not a lot of them. But it's totally up to you :).

**Comment by SamVerschueren** [comment]
Put them in utils.js then :)

**Comment by kevva** [comment]
Changed my mind. As `kap` evolves we might have to create more utils to reflect its changes so I guess we should take that into account right of the bat.

**Review by sindresorhus — APPROVED** [review]

**Comment by SamVerschueren** [comment]
Good point!

For the MockContext, shouldn't override set and get store instead? We expose the entire config object but currently with the mock context, things like `clear()` or `.store` aren't working.

**Comment by kevva** [comment]
Not sure if I'm following here. Doesn't `.clear()` and `.store` work or am I misunderstanding? https://github.com/kevva/kap-plugin-mock-context/blob/mock-conf/test.js#L23-L25

**Comment by SamVerschueren** [comment]
Oeps, on my mobile so harder to check everything :)

**Comment by SamVerschueren** [comment]
Thanks @kevva :beers:!

**Pull request merged**
